#!/bin/bash -p

set -euo pipefail
udevadm settle

args=("install")
cmdline=( $(</proc/cmdline) )

karg() {
    local name="$1" value=""
    for arg in "${cmdline[@]}"; do
        if [[ "${arg%%=*}" == "${name}" ]]; then
            value="${arg#*=}"
        fi
    done
    echo "${value}"
}

#echo "installation_device test export: $installation_device"
# Get install device
installation_device="$(karg coreos.inst.install_dev)"
if [ "${installation_device##*/}" = "${installation_device}" ]; then
    # karg contains no slashes.  Prepend "/dev/" for compatibility.
    installation_device="/dev/${installation_device}"
fi

device=${installation_device##*/}
partition=$(grep -c "${device}"[0-9] /proc/partitions)
echo "installation device: $installation_device and partition $partition"
growpart $installation_device $partition
echo "growpart executed on "$installation_device" "$partition" " 

crypt=$(lsblk -ln -o NAME,TYPE | grep crypt | awk '{print $1}')

if [[ -z ${crypt} ]]; then
    exit 1
fi
cryptsetup resize ${crypt}
echo "cryptsetup resize executed on "${crypt}" "

lvm pvresize /dev/mapper/${crypt}
lvm vgchange -ay rootvg


if [[ ! -e /dev/disk/by-label/root ]]; then
    dm=$(blkid --label root)
    if [[ -z ${dm} ]]; then
        exit 1
    fi
    ln -s ${dm} /dev/disk/by-label/root
fi
echo "mount root device at /growroot \n" 


path_root=/growroot
mkdir -p ${path_root}
mount -t xfs /dev/disk/by-label/root ${path_root}


# path_crypt=/grow_cryptroot
# mkdir -p ${path_crypt}
# device=$(blkid --label crypt_root)
# echo $device
# partition=$(cat "/sys/block/vda/vda4/partition")
# growpart /dev/vda 4


# get devic through coreos.inst

#lvextend +100%FREE (lvs- path of lv)
#tmp_path=$(findmnt -o SOURCE $path -rn)
#path_root=${tmp_path%[*}
#majmin=$(findmnt -nvr -o MAJ:MIN "$path")

#devpath=$(realpath "/sys/dev/block/$majmin")
#partition=$(cat "$devpath/partition")
#parent_path=$(dirname "$devpath")
#parent_device=/dev/$(basename "${parent_path}")
#growpart "${parent_device}" "${partition}" || true



#for my ref
#tmp_path=$(findmnt -o SOURCE / -rn)
#path_root=${tmp_path%[*}
#majmin=$(findmnt -nvr -o MAJ:MIN "$path_root")

#devpath=$(realpath "/sys/dev/block/$majmin")
#partition=$(cat "$devpath/partition")
#parent_path=$(dirname "$devpath")
#parent_device=/dev/$(basename "${parent_path}")

#growpart "${parent_device}" "${partition}" || true