#!/bin/bash

set -euo pipefail
udevadm settle

path=/growroot
mkdir -p ${path}
echo "mount root device at /growroot \n" | systemd-cat
mount -t xfs /dev/disk/by-label/root ${path}

majmin=$(findmnt -nvr -o MAJ:MIN "$path")

devpath=$(realpath "/sys/dev/block/$majmin")
partition=$(cat "$devpath/partition")
parent_path=$(dirname "$devpath")
parent_device=/dev/$(basename "${parent_path}")

growpart "${parent_device}" "${partition}" || true

echo "growpart executed on "${parent_device}" "${partition}" " | systemd-cat

crypt=$(lsblk -ln -o NAME,TYPE | grep crypt | awk '{print $1}')

if [[ -z ${crypt} ]]; then
    exit 1
fi
cryptsetup resize ${crypt}

echo "cryptsetup resize executed on "${dm_name}" " | systemd-cat

lvm pvresize /dev/mapper/${crypt}
lvm vgchange -ay rootvg


if [[ ! -e /dev/disk/by-label/root ]]; then
    dm=$(blkid --label root)
    if [[ -z ${dm} ]]; then
        exit 1
    fi
    ln -s ${dm} /dev/disk/by-label/root
fi

